# Generated by Django 5.1.6 on 2025-03-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('CourseTitle', models.CharField(max_length=100)),
                ('Instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
