# Generated by Django 5.1.6 on 2025-03-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Course',
        ),
    ]
