# Generated by Django 5.1.6 on 2025-03-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contect',
            new_name='content',
        ),
    ]
